dataset: 'coco17'
captions: 'coco'

cfg_name: 'TG-lg'
wandb_project_name: 'USCOCO'


load_weights_from_checkpoint: True
checkpoint: "/staging/leuven/stg_00114/MMMAli/output/2023_04_23_04_08_49_detr_s-43_TG-lg/checkpoints/epoch=68-step=61134.ckpt"
cuda: True
pin_memory: True
num_workers: 12
seed: 43
do_train: False
do_test: True
do_validate_during_training: True
batch_size: 64
val_batch_size: 64
nb_of_pos_bins: 15
lr_schedule: 'linear_with_warmup'
lr_schedule_warmup_epochs: 5
debug: False
debug_num_workers: 0
wandb_offline: False
deterministic: False
use_latent_tree_representations: False
ground_truth_latent_trees: False
use_plm: False
use_tg: True
use_cpn: True
use_smart_filter: True
train:
 gpus: -1
 precision: 32       # todo
 max_steps: -1
 gradient_clip_val: 3.0
text_encoder:
 weight_decay: 0.0
 lr: 0.00
 txt_enc_finetune: False
 txt_enc_pretrained: True

 text_encoder: 'tg'

 hf_model_name_or_path: 'uclanlp/visualbert-vqa-coco-pre'
 hf_tokenizer_model_name_or_path: 'bert-base-uncased'
 tg_checkpoint: '/staging/leuven/stg_00114/transformers-struct-guidance/model/tg_37928.params'
 qian_architecture: 'gpt2-large'
model:
 predict_num_queries: True
 autoregressive: False
 max_target_positions: 96
 length_loss_coef: 0.1
 length_label_smoothing: 0.05
 no_pos_encoding: True
 use_additional_detr_encoder: True

detr:
 dropout: 0.1
 dropout_bbox_embed: 0.1
 dropout_token_embed: 0.1
 weight_decay: 0.01
 noise_as_queries: False
 learnt_query_embeds: True
 query_noise_aggregate: 'sum'        # or 'concat'
 query_pos_first_layer_only: False
 probabilistic_bbox_predictions: False
 aux_loss: False

 lr: 0.0001
 label_smoothing: 0.05
 label_smoothing_pos: 0.05
 set_cost_class_coef: 1.0
 set_cost_bbox_coef: 1.0
 set_cost_giou_coef: 0.4
 set_cost_prob_bbox_coef: 0.0
 prob_bbox_loss_coef: 0.0
 nobj_coef: 0.1
 condition_bbox_prediction_on_label: null  # probs , embed , logits , null , softmax_embed
 softmax_embed_training_argmax_inference: True
