name: uscoco_env
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=11.1
  - python=3.8
  - pytorch>=1.12
  - torchvision
  - tqdm
  - easydict
  - nltk
  - scikit-learn
  - python-dateutil
  - jsonschema
  - transformers=4.28
  - seaborn
  - h5py
  - pip
  - ipython
  - pip:
      - jsonargparse
      - typed-argument-parser
      - pycocotools
      - pytorch-lightning=1.6
      - wandb
      - typed-argument-parser
      - tqdm
      - albumentations
      - iglovikov_helper_functions