dataset: 'coco17'
captions: 'coco'

cfg_name: 'LTP-obj_gan-attngan'
wandb_project_name: 'USCOCO'

continue_training_from_checkpoint: True
checkpoint: "/cw/working-frodo/rubenc/MMMAli/output/2022_06_22_22_21_15_ar_s-41_LTP-obj_gan/checkpoints/last.ckpt"
cuda: True
pin_memory: True
num_workers: 12
seed: 41
do_train: True
do_validate_during_training: True
batch_size: 64
val_batch_size: 64
nb_of_pos_bins: 15
lr_schedule: 'linear_with_warmup'
lr_schedule_warmup_epochs: 5
debug: False
wandb_offline: False
deterministic: False
use_cpn: True
use_smart_filter: True
filter_out_crowds: True
train:
 gpus: -1
 precision: 32       # todo
 gradient_clip_val: 3.0
text_encoder:
 weight_decay: 0.0
 lr: 0.00
 txt_enc_finetune: False
 txt_enc_pretrained: True

 hf_model_name_or_path: 'gpt2'
 hf_tokenizer_model_name_or_path: 'gpt2'
 text_encoder: attn_gan
   #  attn_gan_text_encoder_path: '/scratch/leuven/335/vsc33568/MMMAli/output/2022_02_09_15_06_14_attngan-train_lrg_41/checkpoints/last.ckpt'
   #  attn_gan_text_encoder_path: '/cw/working-frodo/rubenc/MMMAli/output/2022_02_09_15_06_14_attngan-train_lrg_41/checkpoints/last.ckpt'
 attn_gan_text_encoder_path: '/cw/working-eowyn/rubenc/MMMAli/output/2022_04_25_16_04_28_attngan-train-v2-lrg_41/checkpoints/epoch=248-step=588885.ckpt'
 attn_gan_text_encoder_input_dim: 1560
 attn_gan_text_encoder_hidden_dim: 1560
 attn_gan_text_encoder_nlayers: 2
 attn_gan_text_encoder_bidirectional: True
model:
 autoregressive: True
 obj_gan: True
 predict_num_queries: True
 max_target_positions: 24
 length_loss_coef: 0.1
 length_label_smoothing: 0.05

 no_pos_encoding: True
 use_additional_detr_encoder: False
obj_gan:
 input_dim: 1560
 hidden_dim: 128
 box_hidden_dim: 50
 bidirectional_enc: True
detr:
 dropout: 0.1
 dropout_bbox_embed: 0.1
 dropout_token_embed: 0.1
 weight_decay: 0.01
 noise_as_queries: False
 learnt_query_embeds: True
 query_noise_aggregate: 'sum'        # or 'concat'
 query_pos_first_layer_only: False
 probabilistic_bbox_predictions: False
 aux_loss: False

 lr: 0.0001
 label_smoothing: 0.05
 label_smoothing_pos: 0.05
 set_cost_class_coef: 1.0
 set_cost_bbox_coef: 1.0
 set_cost_giou_coef: 0.4
 set_cost_prob_bbox_coef: 0.0
 prob_bbox_loss_coef: 0.0
 bbox_prop_loss_coef: 0.0
 bbox_rel_loss_coef: 0.0
 struct_loss_coef: 0.0
 nobj_coef: 0.1
 condition_bbox_prediction_on_label: null  # probs , embed , logits , null , softmax_embed
 softmax_embed_training_argmax_inference: True
