dataset: 'coco17'
captions: 'coco'

cfg_name: 'plm'
wandb_project_name: 'USCOCO'


cuda: False
pin_memory: True
num_workers: 2
seed: 41
do_train: True
do_validate_during_training: True
batch_size: 128
val_batch_size: 128
nb_of_pos_bins: 15
lr_schedule: 'linear_with_warmup'
lr_schedule_warmup_epochs: 5
debug: True
debug_num_workers: 0
wandb_offline: True
deterministic: False
use_cpn: True
filter_out_crowds: True
save_probe_embeddings: True
save_probe_embeddings_train: False
use_plm: False
use_tg: False
probe:
 batch_size: 12
 h5_path: '/cw/working-theoden/rubenc/MMMAli/output/2022_10_03_16_21_45_detr_s-41_TG/test_run/probe_embeddings.h5'
 h5_index_path: '/cw/working-theoden/rubenc/MMMAli/output/2022_10_03_16_21_45_detr_s-41_TG/test_run/id_to_h5_idx.json'
 learn_negative_constituents: True
 learn_tags: True
 current_layer: 0
train:
 gpus: -1
 precision: 32       # todo
 gradient_clip_val: 3.0
text_encoder:
 weight_decay: 0.0
 lr: 0.00
 txt_enc_finetune: False
 txt_enc_pretrained: True

 text_encoder: qian_base_lm
 hf_model_name_or_path: 'gpt2'
 hf_tokenizer_model_name_or_path: 'gpt2'


 qian_architecture: 'gpt2'
 tg_right_branching: False
 plm_add_structured_mask: True
model:
 predict_num_queries: True
 autoregressive: False
 max_target_positions: 96
 length_loss_coef: 0.1
 length_label_smoothing: 0.05
 encoder_embed_dim: 768
 no_fc_after_text_encoder: True
 no_pos_encoding: True
 use_additional_detr_encoder: True
detr:
 encoder_ffn_embed_dim: 1024
 decoder_ffn_embed_dim: 1024
 dropout: 0.1
 dropout_bbox_embed: 0.1
 dropout_token_embed: 0.1
 weight_decay: 0.01
 noise_as_queries: False
 learnt_query_embeds: True
 query_noise_aggregate: 'sum'        # or 'concat'
 query_pos_first_layer_only: False
 probabilistic_bbox_predictions: False
 aux_loss: False

 lr: 0.0001
 label_smoothing: 0.05
 label_smoothing_pos: 0.05
 set_cost_class_coef: 1.0
 set_cost_bbox_coef: 1.0
 set_cost_giou_coef: 0.4
 set_cost_prob_bbox_coef: 0.0
 prob_bbox_loss_coef: 0.0
 struct_loss_coef: 0.25
 struct_loss_input: tree_pos_embs  # 'encoder_out'  # 'tree_pos_embs'
 nobj_coef: 0.1
 condition_bbox_prediction_on_label: null  # probs , embed , logits , null , softmax_embed
 softmax_embed_training_argmax_inference: True
