dataset: 'coco17'
captions: 'coco'

cfg_name: 'detr-llama-attn50'
wandb_project_name: 'USCOCO'


load_weights_from_checkpoint: True
checkpoint: "/staging/leuven/stg_00114/MMMAli/output/2023_04_21_13_24_00_detr_s-42_detr-llama-attn50/checkpoints/epoch=72-step=129283.ckpt"
cuda: True
pin_memory: True
num_workers: 12
seed: 41
do_train: False
do_test: True
do_validate_during_training: True
batch_size: 64
val_batch_size: 64
nb_of_pos_bins: 15
lr_schedule: 'linear_with_warmup'
lr_schedule_warmup_epochs: 5
debug: False
wandb_offline: False
deterministic: False
use_cpn: True
filter_out_crowds: True
train:
 gpus: -1
 precision: 16       # todo

 gradient_clip_val: 3.0
text_encoder:
 weight_decay: 0.0
 lr: 0.00
 txt_enc_finetune: False
 txt_enc_pretrained: True

 text_encoder: 'huggingface'

 hf_model_name_or_path: '/staging/leuven/stg_00114/llama/hf_llama_7B/'
 hf_tokenizer_model_name_or_path: '/staging/leuven/stg_00114/llama/hf_llama_7B/'
 use_llama: True
model:
 predict_num_queries: True
 autoregressive: False
 max_target_positions: 96
 length_loss_coef: 0.1
 length_label_smoothing: 0.05

 no_pos_encoding: True
detr:
 dropout: 0.1
 dropout_bbox_embed: 0.1
 dropout_token_embed: 0.1
 weight_decay: 0.01
 noise_as_queries: False
 learnt_query_embeds: True
 query_noise_aggregate: 'sum'        # or 'concat'
 query_pos_first_layer_only: False
 probabilistic_bbox_predictions: False
 aux_loss: False

 lr: 0.0001
 label_smoothing: 0.05
 label_smoothing_pos: 0.05
 set_cost_class_coef: 1.0
 set_cost_bbox_coef: 1.0
 set_cost_giou_coef: 0.4
 set_cost_prob_bbox_coef: 0.0
 prob_bbox_loss_coef: 0.0
 struct_loss_coef: 0.50
 struct_loss_type: 'attn'
 struct_loss_input: tree_pos_embs  # 'encoder_out'  # 'tree_pos_embs'
 nobj_coef: 0.1
 condition_bbox_prediction_on_label: null  # probs , embed , logits , null , softmax_embed
 softmax_embed_training_argmax_inference: True
